-- ============================================================
-- Oil & Gas ETL Schema
-- ============================================================

-- ------------------------------------------------------------
-- Imported source PDFs
-- ------------------------------------------------------------

CREATE TABLE source_file (

    id UUID PRIMARY KEY,

    filename TEXT NOT NULL,
    filepath TEXT,

    sha256 TEXT NOT NULL UNIQUE,

    filesize BIGINT,
    page_count INTEGER,

    imported_at TIMESTAMP NOT NULL,

    document_type TEXT,
    parser TEXT,
    parser_version TEXT
);

-- ------------------------------------------------------------
-- Reference Tables
-- ------------------------------------------------------------

CREATE TABLE operator (

    operator_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    operator_name TEXT NOT NULL UNIQUE
);

CREATE TABLE vendor (

    vendor_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    vendor_name TEXT NOT NULL UNIQUE
);

CREATE TABLE expense_category (

    category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    category_name TEXT NOT NULL UNIQUE,

    parent_category TEXT
);

CREATE TABLE cost_center (

    cost_center_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    cost_center_code TEXT UNIQUE,

    description TEXT
);

CREATE TABLE property (

    property_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    operator_id INTEGER
        REFERENCES operator(operator_id),

    property_code TEXT UNIQUE,

    property_name TEXT NOT NULL,

    county TEXT,

    state TEXT,

    api TEXT
);

-- ------------------------------------------------------------
-- Ownership Interest
-- ------------------------------------------------------------

CREATE TABLE ownership_interest (

    interest_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    property_id INTEGER
        REFERENCES property(property_id),

    owner_name TEXT NOT NULL,

    working_interest DECIMAL(12,10),

    revenue_interest DECIMAL(12,10),

    effective_date DATE,

    expiration_date DATE
);

-- ------------------------------------------------------------
-- Revenue Statements (one per check)
-- ------------------------------------------------------------

CREATE TABLE revenue_statement (

    statement_id UUID PRIMARY KEY,

    source_file_id UUID
        REFERENCES source_file(id),

    operator_id INTEGER
        REFERENCES operator(operator_id),

    check_number TEXT,

    check_date DATE,

    check_period DATE,

    gross_revenue DECIMAL(18,2),

    total_deductions DECIMAL(18,2),

    severance_tax DECIMAL(18,2),

    net_revenue DECIMAL(18,2)
);

-- ------------------------------------------------------------
-- Revenue Detail
-- ------------------------------------------------------------

CREATE TABLE revenue_line (

    id UUID PRIMARY KEY,
    statement_id UUID
        REFERENCES revenue_statement(statement_id),
    property_id INTEGER
        REFERENCES property(property_id),
    product TEXT,
    revenue_type TEXT,
    production_period DATE,
    unit_price DECIMAL(18,6),
    property_volume DECIMAL(18,6),
    property_value DECIMAL(18,2),
    owner_interest: DECIMAL(18,10),
    distribution_interest: DECIMAL(18,10),
    owner_volume: DECIMAL(18,6),
    owner_value: DECIMAL(18,2)
);

-- ------------------------------------------------------------
-- JIB Invoice
-- ------------------------------------------------------------

CREATE TABLE jib_invoice (

    invoice_id UUID PRIMARY KEY,

    source_file_id UUID
        REFERENCES source_file(id),

    operator_id INTEGER
        REFERENCES operator(operator_id),

    invoice_number TEXT,

    invoice_date DATE,

    accounting_period DATE,

    invoice_total DECIMAL(18,2),

    payment_status TEXT
);

-- ------------------------------------------------------------
-- JIB Detail
-- ------------------------------------------------------------

CREATE TABLE jib_line (

    id UUID PRIMARY KEY,

    invoice_id UUID
        REFERENCES jib_invoice(invoice_id),

    vendor_id INTEGER
        REFERENCES vendor(vendor_id),

    cost_center_id INTEGER
        REFERENCES cost_center(cost_center_id),

    category_id INTEGER
        REFERENCES expense_category(category_id),

    property_id INTEGER
        REFERENCES property(property_id),

    activity_period DATE,

    afe TEXT,

    op_account TEXT,

    minor_account TEXT,

    description TEXT,

    gross_amount DECIMAL(18,2),

    working_interest DECIMAL(12,10),

    net_amount DECIMAL(18,2)
);

-- ------------------------------------------------------------
-- Extracted PDF Text
-- ------------------------------------------------------------

CREATE TABLE document_page (

    source_file_id UUID
        REFERENCES source_file(id),

    page_number INTEGER,

    page_text TEXT,

    PRIMARY KEY (source_file_id, page_number)
);

-- ------------------------------------------------------------
-- Import History
-- ------------------------------------------------------------

CREATE TABLE import_log (

    id UUID PRIMARY KEY,

    source_file_id UUID
        REFERENCES source_file(id),

    imported_at TIMESTAMP,

    status TEXT,

    rows_inserted INTEGER,

    warnings INTEGER,

    errors INTEGER,

    elapsed_ms INTEGER
);
